title="BTY"

[bty]

#连接钱包用到的用户名
rpcUserName="33exchange"

#连接钱包用到的密码
rpcPassWd="^exchange@2018@fzm@33^`"

#钱包的地址
exchangeaddr="https://172.16.100.116:8085"
#BTY节点的地址,交易发往这个地址上
nodeaddr=["http://47.106.117.142:9801"]

#默认填写BTY
coinType="BTY"

#计划要合并的ERC20的币种名称，大写
#tokenName=""

execer="user.p..coins"


#用来发手续费的地址，在离线地址手续费不足的情况下，会启动分配相应的手续费
feeAddr=""

#发手续费地址对应的私钥,明文
feeAddrKey=""

seed=""

#助记词密码,可命令行配置密码
seedPwd="fzm2018"

#计划合并的数量 float64 浮点类型 如果是整数，务必添加小数点.0 例如200 需要写成200.0
mergeAmount=0.3

#计划合并的目的地址
mergeToAddr=""

#在离线地址手续费不足的时候，向每个地址补充的金额
mergeTxFee=0.001