title="BTY"


[bty]

#连接钱包用到的用户名

rpcUserName="25d04831@gbt@exchange@33"

#连接钱包用到的密码
rpcPassWd="exchange@2019@gbt@33^`"


#钱包的地址
exchangeaddr="https://47.56.67.112:8096"

#BTY节点的地址,交易发往这个地址上
nodeaddr=["http://47.74.191.153:8901"]
#默认填写BTY
coinType="BTY"

#计划要合并的token币种名称，大写

execer="user.p.gbtchain.coins"

coinBase="GBT"

#用来发手续费的地址，在离线地址手续费不足的情况下，会启动分配相应的手续费
feeAddr="1HegeqdZZ2Jx1LotWDZ2zTFBejvPgMvFHD"

#发手续费地址对应的私钥,明文
feeAddrKey="0x0d0affd9cb812eaada72a625649f3180d7da5065cd2cbfdada19337776fe7250"

seed="测 视 游 畅 凉 妹 幅 一 找 充 二 换 晚 酚 巩 跨 三 汁 四 沟 圆 喂 徒 至"

#助记词密码,可命令行配置密码
seedPwd="hl12"

#计划合并的数量 float64 浮点类型 如果是整数，务必添加小数点.0 例如200 需要写成200.0
mergeAmount=1.0

#计划合并的目的地址
mergeToAddr="1P7P4v3kL39zugQgDDLRqxzGjQd7aEbfKs"

#在离线地址手续费不足的时候，向每个地址补充的金额
mergeTxFee=0.001