title="BTY"


[bty]

#连接钱包用到的用户名

rpcUserName="exchange"

#连接钱包用到的密码
rpcPassWd="^exchange@2019@fzm@33^`@ci"


#钱包的地址
exchangeaddr="https://47.52.194.176:16666"

#BTY节点的地址,交易发往这个地址上
nodeaddr=["http://47.91.206.188:8901"]
#默认填写BTY
coinType="BTY"

#计划要合并的token币种名称，大写

execer="user.p.chain.coins"

coinBase="BN"

#用来发手续费的地址，在离线地址手续费不足的情况下，会启动分配相应的手续费
feeAddr="1HegeqdZZ2Jx1LotWDZ2zTFBejvPgMvFHD"

#发手续费地址对应的私钥,明文
feeAddrKey="0x0d0affd9cb812eaada72a625649f3180d7da5065cd2cbfdada19337776fe7250"

seed="请 输 入 相 应 助 记 词 - - - - - - - - - - - - - - -"

#助记词密码,可命令行配置密码
seedPwd="请输入密码"

#计划合并的数量 float64 浮点类型 如果是整数，务必添加小数点.0 例如200 需要写成200.0
mergeAmount=1.0

#计划合并的目的地址
mergeToAddr="1P7P4v3kL39zugQgDDLRqxzGjQd7aEbfKs"

#在离线地址手续费不足的时候，向每个地址补充的金额
mergeTxFee=0.001